### ISSUE TITLE
Material caching is not working properly

### ISSUE THREAD

**Issue by kwasak** [mob-sakai/UIEffect#163] opened 2019-04-10 02:04 UTC
UIEffectBase.OnValidate() is increasing the amount of time it takes to enter playmode. In my project, UIEffectBase.OnValidate is adding an extra 2s.

![Screen Shot 2019-04-09 at 10 01 03 PM](https://user-images.githubusercontent.com/1744202/55846332-516b3f00-5b13-11e9-998e-7fcd2b95f954.png)

**Comment by mob-sakai** [comment] 2019-04-10 02:48
Hi @kwasak 
Thank you for reporting.

I would like to know more information on this issue.
Unity version, platform, more profiler infomation...

**Comment by kwasak** [comment] 2019-04-10 05:37
You’re welcome!
Unity 2018.3, iOS.

For the profiler information, the attached screenshot is all I got for profiler information.


On Apr 9, 2019, at 10:48 PM, Takashi Sakai <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @kwasak<https://github.com/kwasak>
Thank you for reporting.

I would like to know more information on this issue.
Unity version, platform, more profiler infomation...

**Comment by mob-sakai** [comment] 2019-04-12 01:35
Thank you, @kwasak !
Can you submit a reproducible project for this issue?
It helps me to resolve the issue.

**Comment by kwasak** [comment] 2019-05-24 17:31
Sorry, this took so long. I'm on a tight schedule with a project I'm working on.
It appears the issue stems from a call to `MaterialResolver.GetOrGenerateMaterialVariant()`from UIShiny.

`MaterialResolver.GetOrGenerateMaterialVariant()`_calls_ `GetMaterial()` which makes an expensive call to `AssetDatabase.FindAsset()`. This call occurs for every UIShiny object in the scene.

As you can see from the attached image, in my case, this adds 3.7s to Assembly Reload Time.
As`GetOrGenerateMaterialVariant()` is called from `OnValidate()`.

From what I see, the solution would be cache the material received from `GetMaterial()`.

![Screen Shot 2019-05-24 at 1 20 50 PM](https://user-images.githubusercontent.com/1744202/58345627-ce821780-7e26-11e9-84bd-098285769dac.png)

UISmartShiny is a class I inherited from UIShiny, for the purpose of this bug their identical, this occurs in both my version and the original UIShiny.

I hope this helps, I apologize again for the late reply.

**Comment by mob-sakai** [comment] 2019-05-25 00:06
@kwasak 
Oh, sorry.
I missed this issue.
I will fix it soon.

**Comment by mob-sakai** [comment] 2019-05-25 00:33
WIP
![image](https://user-images.githubusercontent.com/12690315/58362249-1c9f2580-7ed0-11e9-97c0-2961cb142478.png)

GC: 41.4MB -> 232.5KB

**Comment by kwasak** [comment] 2019-05-25 02:46
Awesome, great improvement.
41MB to 232KB is amazing!


On May 24, 2019, at 8:33 PM, Takashi Sakai <notifications@github.com<mailto:notifications@github.com>> wrote:


WIP
[image]<https://user-images.githubusercontent.com/12690315/58362249-1c9f2580-7ed0-11e9-97c0-2961cb142478.png>

GC: 41.4MB -> 232.5KB

**Comment by mob-sakai** [comment] 2019-05-25 10:23
The cause of the problem is that the material cache was not working properly.
If there is no problem, it will be released.
Try it on your project. :)

**Closed** 2019-06-30 14:12 UTC
Labels: bug
