### ISSUE TITLE
When "UI-Effect.mat" is created automatically, Unity hangs up.

### ISSUE THREAD

**Issue by shirou-take** [mob-sakai/UIEffect#126] opened 2018-09-05 09:43 UTC
Hi.

When GetOrGenerateMaterialVariant () in MaterialResolver.cs is executed without UI-Effect.mat, AssetDatabase.CreateAsset () fails and Unity hangs up.

1.Create New Project in UnityEditor.(Unity2018.2.5f1)
2.Import UIEffect.unitypackage(v2.8.1)
3.Remove /Assets/Coffee/UIExtensions/UIEffect/Materials/UI-Effect.mat
4.Load /Assets/Coffee/UIExtensions/UIEffect/Demo/UIEffec_Demo.unity
5.Unity hangs up

I have a log, should I paste it?

**Comment by mob-sakai** [comment] 2018-09-05 12:11
Hi @shirou-take

Wow, thank you for finding the bug!
Please paste the log:)

**Comment by shirou-take** [comment] 2018-09-06 03:13
Hi @mob-sakai 

This is a log when it hangs up
[Editor.zip](https://github.com/mob-sakai/UIEffect/files/2355158/Editor.zip)

This log is from the time of manually erasing UI-Effect.mat. (not full size log)

After this, the last error(stack trace) is repeated indefinitely.

**Comment by mob-sakai** [comment] 2018-09-06 04:07
Thunks a lot!

**Comment by mob-sakai** [comment] 2018-09-10 15:09
This issue is reproduced in Unity2017.x or above.
It is a little fussy, **but I will fix it with v3.0.0.**

### Solution for this issue

If you encounter this issue, please try the following steps:
1. Delete UIEffect directory (`Assets/Coffee/UIExtensions/UIEffect` or `Assets/UIEffect`).
2. reinstall `UIEffect.unitypackage` from [releases](https://github.com/mob-sakai/UIEffect/releases).

**Comment by shirou-take** [comment] 2018-09-13 05:44
Hi @mob-sakai 
I am glad that you can fix it!
I am waiting for v3.0.0.

**Comment by mob-sakai** [comment] 2018-09-23 05:34
Due to the delay in the v3.0.0 release, this bug will be fixed in v2.9.0.

**Closed** 2018-09-26 13:04 UTC
Labels: bug
