### ISSUE TITLE
Enable/Disable the gameobject then UIShiny script brokes the image.

### ISSUE THREAD

**Issue by nidaynere** [mob-sakai/UIEffect#189] opened 2019-09-08 08:46 UTC
**Describe the bug**
Enable/Disable the gameobject then UIShiny script brokes the image.

**To Reproduce**
1. Create a UI image and add UIShiny script.
2. Disable gameobject then enable.
3. See the error.

**Environment (please complete the following information):**
 - Platform: Windows
 - Unity: 2019.2.a8
 - UIEffect: 3.2.0

**Comment by mob-sakai** [comment] 2019-10-29 00:39
Hi @nidaynere 

Sorry for my late reply.
The issue is reproduced.
Perhaps the material & the parameter texture cause this bug.
It will be fixed in v4.

**Comment by mayura33** [comment] 2019-11-06 10:07
For the temporary fix you could try Image component disable and enable and after that set image null then again set image with your image path.(I know its kinda weird but it works in my case) XD.

**Closed** 2020-08-30 15:06 UTC
Labels: bug, released on @preview
